version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  order-service:
    depends_on:
      - "order_db"
    container_name: order-service
    ports:
      - "5021:5021"
    build: .
    networks:
      - dev

  order_db:
    image: postgres:latest
    container_name: order_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - order_data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  order_data: